### ISSUE TITLE
Handle color keywords

### ISSUE THREAD

**Issue by rnons** [nonbili/purescript-css-properties#1]
1. `getValues "color"` should return a list of [color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
2. Same for `getValues "background-color"` and `getValues "border-color"`
3. Please add some tests, don't forget to test `transparent` and `currentColor`

I think we should be able to get the color keywords list from csstree.

I just realized there are more `*-color` [css properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference), ideally we should use csstree syntax to find out which property accepts `<color>` value, and return the color keywords in `getValues "*-color"`.

**Comment by kahlil29** [comment]
I will be attempting to solve this issue 😄
